test ci signing

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,8 +3,8 @@ name: Build/release
 on:
   workflow_dispatch:
   push:
-    tags:
-      - 'v*'
+    #tags:
+    #  - 'v*'
 
 jobs:
   meta:
@@ -21,33 +21,34 @@ jobs:
           PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
           echo "current-version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT
           echo "current-version=${PACKAGE_VERSION}"
-  docker:
-    runs-on: ubuntu-latest
-    needs : meta
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v5
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Build and push
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          push: ${{ github.event_name != 'pull_request' }}
-          tags: |
-            ghcr.io/l-atelier-des-chercheurs/dodoc:${{needs.meta.outputs.dodoc-version}}
-            ghcr.io/l-atelier-des-chercheurs/dodoc:latest
+  #docker:
+  #  runs-on: ubuntu-latest
+  #  needs : meta
+  #  steps:
+  #    - name: Checkout
+  #      uses: actions/checkout@v5
+  #    - name: Login to GitHub Container Registry
+  #      uses: docker/login-action@v3
+  #      with:
+  #        registry: ghcr.io
+  #        username: ${{ github.repository_owner }}
+  #        password: ${{ secrets.GITHUB_TOKEN }}
+  #    - name: Build and push
+  #      uses: docker/build-push-action@v6
+  #      with:
+  #        context: .
+  #        push: ${{ github.event_name != 'pull_request' }}
+  #        tags: |
+  #          ghcr.io/keomabrun/dodoc:${{needs.meta.outputs.dodoc-version}}
+  #          ghcr.io/keomabrun/dodoc:latest
 
   electron:
     runs-on: ${{ matrix.os }}
-    needs : meta
+    needs: meta
     strategy:
       matrix:
-        os: [ubuntu-latest, windows-latest, macos-latest]
+        #os: [ubuntu-latest, windows-latest, macos-latest]
+        os: [macos-latest]
     steps:
       - name: Check out Git repository
         uses: actions/checkout@v4
@@ -68,4 +69,18 @@ jobs:
           npm install
           cd electron
           npm install
+
+          # Verify environment variables are set (without showing values)
+          if [ -z "$APPLE_ID" ] || [ -z "$APPLE_APP_SPECIFIC_PASSWORD" ]; then
+            echo "❌ ERROR: APPLE_ID or APPLE_APP_SPECIFIC_PASSWORD is not set!"
+            exit 1
+          fi
+
           npm run dist
+      - name: check macOS image
+        run: |
+          echo "🔍 verify code signature"
+          codesign -dv electron/dist/mac-arm64/do•doc.app
+          codesign -dv electron/dist/dodoc-13.0.10-macos.dmg
+          #spctl -a -vvv -t install electron/dist/dodoc-13.0.10-macos.dmg
+        if: matrix.os == 'macos-latest'
